### ISSUE TITLE
Problem with TelephonyComponentFactory

### ISSUE THREAD

**Issue by mj1687** [AOSPA/android_frameworks_opt_telephony#3]
HI aospa team, i'm using your opt telephony for build a new caf rom. in every build in the logcat i have this errror

02-01 19:52:52.720 13158 13158 W System  : ClassLoader referenced unknown path: /system/priv-app/TelephonyProvider/lib/arm
02-01 19:52:52.721 13158 13158 D ApplicationLoaders: ignored Vulkan layer search path /system/priv-app/TelephonyProvider/lib/arm:/system/priv-app/TelephonyProvider/TelephonyProvider.apk!/lib/armeabi-v7a:/system/lib:/vendor/lib for namespace 0xb4dab090
02-01 19:52:52.737 13158 13158 D TelephonyProvider: dbh.onOpen: ok, queried table=siminfo
02-01 19:52:52.738 13158 13158 D TelephonyProvider: dbh.onOpen: ok, queried table=carriers
02-01 19:52:52.754 13158 13158 W System  : ClassLoader referenced unknown path: /system/framework/qti-telephony-common.jar
02-01 19:52:52.756 13158 13158 W System.err: java.lang.ClassNotFoundException: com.qualcomm.qti.internal.telephony.QtiTelephonyComponentFactory
02-01 19:52:52.756 13158 13158 W System.err: 	at java.lang.Class.classForName(Native Method)
02-01 19:52:52.756 13158 13158 W System.err: 	at java.lang.Class.forName(Class.java:400)
02-01 19:52:52.756 13158 13158 W System.err: 	at com.android.internal.telephony.TelephonyComponentFactory.getInstance(TelephonyComponentFactory.java:71)
02-01 19:52:52.756 13158 13158 W System.err: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhone(PhoneFactory.java:133)
02-01 19:52:52.756 13158 13158 W System.err: 	at com.android.internal.telephony.PhoneFactory.makeDefaultPhones(PhoneFactory.java:91)
02-01 19:52:52.757 13158 13158 W System.err: 	at com.android.phone.PhoneGlobals.onCreate(PhoneGlobals.java:282)
02-01 19:52:52.757 13158 13158 W System.err: 	at com.android.phone.PhoneApp.onCreate(PhoneApp.java:41)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1025)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5453)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.app.ActivityThread.-wrap2(ActivityThread.java)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1556)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.os.Looper.loop(Looper.java:154)
02-01 19:52:52.757 13158 13158 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6169)
02-01 19:52:52.757 13158 13158 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
02-01 19:52:52.757 13158 13158 W System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
02-01 19:52:52.757 13158 13158 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:778)
02-01 19:52:52.758 13158 13158 W System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.qualcomm.qti.internal.telephony.QtiTelephonyComponentFactory" on path: DexPathList[[],nativeLibraryDirectories=[/system/lib, /vendor/lib]]
02-01 19:52:52.758 13158 13158 W System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
02-01 19:52:52.758 13158 13158 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
02-01 19:52:52.758 13158 13158 W System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
02-01 19:52:52.758 13158 13158 W System.err: 	... 17 more
02-01 19:52:52.827  1397  1397 D KeyguardUpdateMonitor: received broadcast android.intent.action.SIM_STATE_CHANGED
02-01 19:52:52.827  1397  1397 V KeyguardUpdateMonitor: action android.intent.action.SIM_STATE_CHANGED state: NOT_READY slotId: 0 subid: -2
02-01 19:52:52.828  1397  1397 D KeyguardUpdateMonitor: handleSimStateChange(subId=-2, slotId=0, state=

the part of your code that apparently create the problem was added in this commit: https://github.com/AOSPA/android_frameworks_opt_telephony/commit/94fdae08fbc67ed1f847e30a3c446a71e909ce95

The build is on Nexus 6, the vendor are from PureNexus.

if this isn't a your error please tell me where i am wrong

**Comment by lucasponez** [comment]
Did you find a solution, friend?
